### PR TITLE
Fix reboot container docker

### PR DESCRIPTION
**Pull request by martiou**
The container docker Tuleap starts well the first time.
At the restart of the container, Tuleap no longer works: issues # 35, # 33 ...

After several tests, I fixed the problem as follows:

1) For mysql, i've changed the my.cnf file located in /data/etc :
```
#datadir=/var/lib/mysql
datadir=/data/lib/mysql
#socket=/data/lib/mysql/mysql.sock
socket=/var/lib/mysql/mysql.sock
```
Indeed the paths point by default in /var/lib/mysql at the restart of the container: the sources tuleap-bin.000 ***, directory tuleap, ... are not present and the server mysql can not start. It seems that the error on the boot-fixpath.sh (see below 2)) have blocked the creation of the symbolic link `ln -s /data/lib/mysql mysql`

The default mysql.sock in persistent data /data/lib/mysql/mysql.sock does not seem to work for docker, i've replacing the socket in /var/lib/mysql/mysql.sock

------------------------------------------------------------------------------------------------------
2) Once the mysql problem is fixed, it's apache's turn.
Similar concern, the system expects confs at /etc/httpd/conf and /etc/httpd/conf.d, by default these reboot directories no longer exist.

I've modified boot-fixpath.sh for global prevent  existing symbolic links error (view zip joined).

Exemple of error with permanent existing symbolic links (not deleted at the beginning : It's a "reboot", just discard image default) :
```
cd /etc/pki/tls/private
ln -s /data/etc/pki/tls/private/localhost.key localhost.key

cd /etc/ssl/certs
ln -s /data/etc/ssl/certs/localhost.crt localhost.crt
```

And with correction now :
```
cd /etc/pki/tls/private
[ ! -f localhost.key ] && ln -s /data/etc/pki/tls/private/localhost.key localhost.key
cd /etc/ssl/certs
[ ! -f localhost.crt ] && ln -s /data/etc/ssl/certs/localhost.crt localhost.crt
```

=> these two lines in error above (before correction) have misled the startup of Apache because the following links were not created: :
```
cd /etc/httpd
ln -s /data/etc/httpd/conf conf
ln -s /data/etc/httpd/conf.d conf.d
```
=> Same problem for mysql :
```
cd /var/lib
ln -s /data/lib/mysql mysql
```
------------------------------------------------------------------------------------------------------
When I restart the container docker Tuleap, It's work good.
------------------------------------------------------------------------------------------------------
[boot-fixpath.zip](https://github.com/Enalean/docker-tuleap-aio/files/1454425/boot-fixpath.zip)

### CODE REVIEW

**Comment by vaceletm** [comment]
Thanks for proposing a PR but it seems that you didn't manage to got it right.

Here you want to merge "master" branch to deprecated "centos6" branch.

**Comment by LeSuisse** [comment]
To avoid any confusion we have done some cleanup in the repo and drop the old `centos5` and `centos6` branches.

**Comment by martiou** [comment]
Hello, it was my first PR and i have not find how to do something for boot-fixpath.sh, sorry...
With the last installation docker, I've the same problem on reboot container : 
Logs : 
```
10T13:28:27.156018579Z + cd /usr/share/tuleap/tools/docker/tuleap-aio
10T13:28:27.156025740Z + TULEAP_INSTALL_TIME=false
10T13:28:27.156041524Z + '[' '!' -f /data/etc/tuleap/conf/local.inc ']'
10T13:28:27.156048981Z + ./boot-fixpath.sh
>> error :
10T13:28:27.191563946Z ln: creating symbolic link `localhost.key': File exists
```
And it's impossible to do something : 
```
docker exec -ti tuleap bash
Error response from daemon: Container 458258c3ac88fe48a653430ebae871f5c5ceee96fd5d84ee65404020500bd8b5 is restarting, wait until the container is running
```

Steps for working good :
1) I have stop and delete container. 
2) Run a new container : 
docker run -ti --restart="always" -d --env VIRTUAL_HOST="localhost"  --name=tuleap -p 443:443 -p 80:80 -p 6982:22 -v /produits/volumes_docker/tuleap_data:/data enalean/tuleap-aio
3) Go to the container with docker exec -ti tuleap bash
4) In /usr/share/tuleap/tools/docker/tuleap-aio, just make change :
```
cd /etc/pki/tls/private
[ ! -f localhost.key && ln -s /data/etc/pki/tls/private/localhost.key localhost.key

cd /etc/ssl/certs
[ ! -f localhost.crt && ln -s /data/etc/ssl/certs/localhost.crt localhost.crt
```

5) Reboot Tuleap docker container ok

**Comment by vaceletm** [comment]
Your changes were taken into account in this change: https://gerrit.tuleap.net/#/c/9896/

It's not merged yet so it's no surprise that it doesn't work with latest image version

Please note that the image was meant so containers are not kept and should be removed on rather than stop/start/restart

**Comment by martiou** [comment]
Thank you for your reply.
In my company, servers restart every night, active containers must be able to resume as well ...

**Pull request closed without merging**
